version: 2
jobs:
  validate:
    docker:
      - image: hashicorp/packer:1.6.0
    working_directory: ~/packer
    steps:
      - checkout
      - run:
          name: Validate packer template
          command: packer validate ./influxdb.json
  build:
    docker:
      - image: hashicorp/packer:1.6.0
    working_directory: ~/packer
    steps:
      - checkout
      - attach_workspace:
          at: ~/packer
      - run:
          name: Build image
          command: packer build influxdb.json
          no_output_timeout: 30s
      - persist_to_workspace:
          root: .
          paths:
            - manifest.json
      - store_artifacts:
          path: manifest.json
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - validate
      - build:
          requires:
            - validate
          filters:
            branches:
              only:
                - master
