---
AWSTemplateFormatVersion: '2010-09-09'
Description: This master template creates a VPC infrastructure for a multi-AZ,
  multi-tier InfluxDB Enterprise deployment on AWS. It deploys a VPC with
  bastions and an InfluxDB cluster behind an ALB. The cluster is configured to
  use EBS io1 volumes for storage **WARNING** This template creates EC2
  instances and related resources. You will be billed for the AWS resources and
  InfluxDB Enterprise license (via AWS Marketplace) used if you create a stack
  from this template. This template requires a subscription to the InfluxDB
  Enterprise offer on AWS Marketplace.
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
    - Label:
        default: Network configuration
      Parameters:
      - AvailabilityZone1
      - AvailabilityZone2
      - AvailabilityZone3
      - VPCCIDR
      - PrivateSubnet1CIDR
      - PrivateSubnet2CIDR
      - PrivateSubnet3CIDR
      - PublicSubnet1CIDR
      - PublicSubnet2CIDR
      - PublicSubnet3CIDR
      - RemoteAccessCIDR
    - Label:
        default: InfluxDB EC2 configuration
      Parameters:
      - KeyPairName
      - BastionAMIOS
      - BastionInstanceType
      - DataNodeInstanceType
      - DataNodeDiskSize
      - DataNodeDiskIOPS
      - MetaNodeInstanceType
      - MonitorNodeInstanceType
    - Label:
        default: InfluxDB cluster configuration
      Parameters:
      - NumberOfInfluxDBDataNodes
      - InfluxDBUsername
      - InfluxDBPassword
      - InfluxDBAccessCIDR
    - Label:
        default: AWS Quick Start configuration
      Parameters:
      - TemplateS3BucketName
      - TemplateS3BucketRegion
      - TemplateS3KeyPrefix
    ParameterLabels:
      AvailabilityZone1:
        default: Availability Zone for subnet 1
      AvailabilityZone2:
        default: Availability Zone for subnet 2
      AvailabilityZone3:
        default: Availability Zone for subnet 3
      BastionAMIOS:
        default: Bastion AMI operating system
      BastionInstanceType:
        default: Bastion instance type
      DataNodeInstanceType:
        default: InfluxDB data node instance type
      DataNodeDiskSize:
        default: InfluxDB data node disk size
      DataNodeDiskIOPS:
        default: InfluxDB data node disk IOPS
      InfluxDBUsername:
        default: InfluxDB admin username
      InfluxDBPassword:
        default: InfluxDB admin password
      InfluxDBAccessCIDR:
        default: Allowed InfluxDB external access CIDR
      KeyPairName:
        default: Key pair name
      MetaNodeInstanceType:
        default: InfluxDB meta node instance type
      MonitorNodeInstanceType:
        default: InfluxDB monitor node instance type
      NumberOfInfluxDBDataNodes:
        default: Number of InfluxDB data nodes
      PrivateSubnet1CIDR:
        default: Private subnet 1 CIDR
      PrivateSubnet2CIDR:
        default: Private subnet 2 CIDR
      PrivateSubnet3CIDR:
        default: Private subnet 3 CIDR
      PublicSubnet1CIDR:
        default: Public subnet 1 CIDR
      PublicSubnet2CIDR:
        default: Public subnet 2 CIDR
      PublicSubnet3CIDR:
        default: Public subnet 3 CIDR
      TemplateS3BucketName:
        default: Quick Start S3 bucket name
      TemplateS3BucketRegion:
        default: Quick Start S3 bucket region
      TemplateS3KeyPrefix:
        default: Quick Start S3 Key Prefix
      RemoteAccessCIDR:
        default: Allowed bastion external access CIDR
      VPCCIDR:
        default: VPC CIDR
Parameters:
  AvailabilityZone1:
    Description: >-
      Availability Zone to use for subnet 1 in the VPC. Only
      three Availability Zones are used for this deployment.
    Type: AWS::EC2::AvailabilityZone::Name
  AvailabilityZone2:
    Description: >-
      Availability Zone to use for subnet 2 in the VPC. Only
      three Availability Zones are used for this deployment.
    Type: AWS::EC2::AvailabilityZone::Name
  AvailabilityZone3:
    Description: >-
      Availability Zone to use for subnet 3 in the VPC. Only
      three Availability Zones are used for this deployment.
    Type: AWS::EC2::AvailabilityZone::Name
  BastionAMIOS:
    AllowedValues:
      - Amazon-Linux2-HVM
      - CentOS-7-HVM
      - Ubuntu-Server-20.04-LTS-HVM
      - SUSE-SLES-15-HVM
    Default: Amazon-Linux2-HVM
    Description: Linux distribution for the AMI to be used for the bastion instance.
    Type: String
  BastionInstanceType:
    Default: t2.micro
    Description: Amazon EC2 instance type for the bastion instance.
    Type: String
  DataNodeInstanceType:
    Default: m5.xlarge
    Description: Type of EC2 instance for InfluxDB data nodes.
    Type: String
  DataNodeDiskSize:
    Default: 250
    Description: Size in GB of the EBS io1 volume attached to each data node.
    Type: Number
  DataNodeDiskIOPS:
    Default: 1000
    Description: Provisioned IOPS of the EBS io1 volume on each data node.
    Type: Number
  InfluxDBUsername:
    Description: Username for the initial InfluxDB admin user.
    Type: String
  InfluxDBPassword:
    Description: Password for initial InfluxDB admin user.
    Type: String
  InfluxDBAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: >-
      CIDR IP range that is permitted to access the InfluxDB cluster. We recommend
      that you set this value to a trusted IP range.
    Type: String
  KeyPairName:
    Description: Name of an existing public/private key pair, which allows you
      to securely connect to your instance after it launches.
    Type: AWS::EC2::KeyPair::KeyName
  MetaNodeInstanceType:
    AllowedValues:
      - t2.small
      - t2.medium
      - t2.large
      - t3.small
      - t3.medium
      - t3.large
    Default: t3.small
    Description: Type of EC2 instance for InfluxDB meta nodes.
    Type: String
  MonitorNodeInstanceType:
    Default: t3.small
    Description: >-
      Type of EC2 instance configured to monitor InfluxDB cluster with Chronograf and Kapacitor.
    Type: String
  NumberOfInfluxDBDataNodes:
    AllowedValues:
      - '2'
      - '4'
      - '6'
      - '8'
      - '12'
      - '16'
    Default: '2'
    Description: Number of InfluxDB data nodes to use in the cluster.
    Type: String
  PrivateSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/19
    Description: CIDR block for private subnet 1 located in Availability Zone 1.
    Type: String
  PrivateSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.32.0/19
    Description: CIDR block for private subnet 2 located in Availability Zone 2.
    Type: String
  PrivateSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.32.0/19
    Description: CIDR block for private subnet 3 located in Availability Zone 3.
    Type: String
  PublicSubnet1CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.128.0/20
    Description: CIDR block for the public (DMZ) subnet 1 located in Availability
      Zone 1.
    Type: String
  PublicSubnet2CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: CIDR block for the public (DMZ) subnet 2 located in Availability
      Zone 2.
    Type: String
  PublicSubnet3CIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.144.0/20
    Description: CIDR block for the public (DMZ) subnet 3 located in Availability
      Zone 3.
    Type: String
  InfluxDBTemplateURL:
    Default: https://aws-marketplace-influxdata.s3.amazonaws.com/enterprise/templates/influxdb-enterprise.yaml
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  TemplateS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    Type: String
  TemplateS3BucketRegion:
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (TemplateS3BucketName) is hosted. When using your own bucket, you must specify this value.'
    Type: String
  TemplateS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: aws-marketplace-influxdata/v1/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    Type: String
  RemoteAccessCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/x
    Description: CIDR IP range that is permitted to access the bastions. We recommend
      that you set this value to a trusted IP range.
    Type: String
  VPCCIDR:
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/16
    Description: CIDR block for the VPC.
    Type: String
Conditions:
  UsingDefaultBucket: !Equals [!Ref TemplateS3BucketName, 'aws-quickstart']
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${TemplateS3KeyPrefix}submodules/quickstart-aws-vpc/templates/aws-vpc.template'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref TemplateS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${TemplateS3BucketName}-${AWS::Region}', !Ref TemplateS3BucketName]
      Parameters:
        AvailabilityZones:
          Fn::Join:
          - ','
          - - Ref: AvailabilityZone1
            - Ref: AvailabilityZone2
            - Ref: AvailabilityZone3
        KeyPairName:
          Ref: KeyPairName
        NumberOfAZs: '3'
        PrivateSubnet1ACIDR:
          Ref: PrivateSubnet1CIDR
        PrivateSubnet2ACIDR:
          Ref: PrivateSubnet2CIDR
        PrivateSubnet3ACIDR:
          Ref: PrivateSubnet3CIDR
        PublicSubnet1CIDR:
          Ref: PublicSubnet1CIDR
        PublicSubnet2CIDR:
          Ref: PublicSubnet2CIDR
        PublicSubnet3CIDR:
          Ref: PublicSubnet3CIDR
        VPCCIDR:
          Ref: VPCCIDR
  BastionStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${TemplateS3KeyPrefix}submodules/quickstart-linux-bastion/templates/linux-bastion.template'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref TemplateS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${TemplateS3BucketName}-${AWS::Region}', !Ref TemplateS3BucketName]
      Parameters:
        TemplateS3BucketName:
          Ref: TemplateS3BucketName
        TemplateS3BucketRegion:
          Ref: TemplateS3BucketRegion
        TemplateS3KeyPrefix: !Sub '${TemplateS3KeyPrefix}submodules/quickstart-linux-bastion/'
        BastionAMIOS:
          Ref: BastionAMIOS
        BastionInstanceType:
          Ref: BastionInstanceType
        KeyPairName:
          Ref: KeyPairName
        PublicSubnet1ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1ID
        PublicSubnet2ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2ID
        PublicSubnet3ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet3ID
        RemoteAccessCIDR:
          Ref: RemoteAccessCIDR
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID
  InfluxDBStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub
          - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${TemplateS3KeyPrefix}templates/influxdb-enterprise-yaml.template'
          - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref TemplateS3BucketRegion]
            S3Bucket: !If [UsingDefaultBucket, !Sub '${TemplateS3BucketName}-${AWS::Region}', !Ref TemplateS3BucketName]
      Parameters:
        AvailabilityZone1:
          Ref: AvailabilityZone1
        AvailabilityZone2:
          Ref: AvailabilityZone2
        AvailabilityZone3:
          Ref: AvailabilityZone3
        BastionSecurityGroupID:
          Fn::GetAtt:
          - BastionStack
          - Outputs.BastionSecurityGroupID
        DataNodeInstanceType:
          Ref: DataNodeInstanceType
        DataNodeDiskSize:
          Ref: DataNodeDiskSize
        DataNodeDiskIOPS:
          Ref: DataNodeDiskIOPS
        InfluxDBUsername:
          Ref: InfluxDBUsername
        InfluxDBPassword:
          Ref: InfluxDBPassword
        InfluxDBAccessCIDR:
          Ref: InfluxDBAccessCIDR
        KeyPairName:
          Ref: KeyPairName
        MetaNodeInstanceType:
          Ref: MetaNodeInstanceType
        MonitorNodeInstanceType:
          Ref: MonitorNodeInstanceType
        NumberOfInfluxDBDataNodes:
          Ref: NumberOfInfluxDBDataNodes
        PrivateSubnet1ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet1AID
        PrivateSubnet2ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet2AID
        PrivateSubnet3ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PrivateSubnet3AID
        PublicSubnet1ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet1ID
        PublicSubnet2ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet2ID
        PublicSubnet3ID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.PublicSubnet3ID
        VPCID:
          Fn::GetAtt:
          - VPCStack
          - Outputs.VPCID